# Generated by Django 5.0.1 on 2024-03-06 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_product_str_id_alter_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='price',
            name='str_id',
            field=models.CharField(default=None, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price_id',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='price',
            name='currency',
            field=models.CharField(default=None, max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
