# Generated by Django 5.0.1 on 2024-03-06 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_remove_product_price_price_str_id_product_price_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price_id',
            new_name='price_name',
        ),
    ]
