# Generated by Django 5.0.1 on 2024-03-06 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_rename_price_id_product_price_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='product_name',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price_name',
            new_name='price_id',
        ),
    ]
