# Generated by Django 5.0.1 on 2024-03-08 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_rename_product_name_price_product_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_id',
        ),
        migrations.AlterField(
            model_name='product',
            name='str_id',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
