# Generated by Django 5.0.1 on 2024-03-08 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_remove_product_price_id_alter_product_str_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='currency',
            field=models.CharField(default='rub', max_length=3),
        ),
    ]
