# Generated by Django 5.0.1 on 2024-03-08 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_alter_price_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='str_id',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
