# Generated by Django 5.0.1 on 2024-03-09 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_alter_price_str_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.product'),
        ),
    ]
