# Generated by Django 5.0.1 on 2024-03-09 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_alter_course_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='price',
        ),
        migrations.AddField(
            model_name='course',
            name='price_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
